Repository aaossa/git-activity, pull requests merged in 2022-06, with the labels that each got.

#5 Mac support
  git-activity
Labels: bug, enhancement

#4 feature: Refactor color selections to support 8-bit colors...
  git-activity
Labels: bug, enhancement

#1 add(docs): add a guide about how to run on Mac
  README.md
Labels: documentation, enhancement

#7 Only display first 3 letters of months' names
  git-activity
Labels: bug
